-- Generated by scripts/generate-impacted.js
-- Source: 2025-10-04T21:36:00.011Z

RipAddons_ImpactedData = {
  version = "2025-10-04",
  addons = {
    ["consoleport"] = { severity = "low", note = "Console port addon is safe", link = "https://reddit.com/r/wow/comments/1nwxxe8/ion_confirms_that_the_consoleport_addon_will/" },
    ["mythicdungeontools"] = { severity = "low", note = "Day 1 Addons Update", link = "https://us.forums.blizzard.com/en/wow/t/day-1-alpha-ui-and-addons-update/2177122" },
    ["rclootcouncil"] = { severity = "low", note = "Day 1 Addons Update", link = "https://us.forums.blizzard.com/en/wow/t/day-1-alpha-ui-and-addons-update/2177122" },
    ["weakauras"] = { severity = "critical", note = "No WeakAuras Addon for Midnight", link = "https://www.wowhead.com/news/no-weakauras-addon-for-midnight-378740" },
  }
}
