-- Generated by scripts/generate-impacted.js
-- Source: 2025-11-12T05:33:11.381Z

RipAddons_ImpactedData = {
  version = "2025-11-12",
  addons = {
    ["bigwigs"] = { severity = "high", note = "DBM (and likely BigWigs) are due to lose most functionality in Midnight - DBM Author", link = "https://www.youtube.com/watch?v=RGcvWICMXWw" },
    ["consoleport"] = { severity = "low", note = "Console port addon is safe", link = "https://reddit.com/r/wow/comments/1nwxxe8/ion_confirms_that_the_consoleport_addon_will/" },
    ["dbm"] = { severity = "high", note = "DBM (and likely BigWigs) are due to lose most functionality in Midnight - DBM Author", link = "https://www.youtube.com/watch?v=RGcvWICMXWw" },
    ["elvui"] = { severity = "critical", note = "Development of ElvUI for Midnight is now officially on hold", link = "https://www.mmo-champion.com/threads/2664900-Midnight-Addon-Apocalypse" },
    ["grid2"] = { severity = "high", note = " Midnight Addon Apocalypse", link = "https://www.mmo-champion.com/threads/2664900-Midnight-Addon-Apocalypse" },
    ["healbot"] = { severity = "high", note = " Midnight Addon Apocalypse", link = "https://www.mmo-champion.com/threads/2664900-Midnight-Addon-Apocalypse" },
    ["hekili"] = { severity = "critical", note = "Hekili Dev Announces End of Addon", link = "https://old.reddit.com/r/wow/comments/1nvkwgt/hekili_addon_will_not_continue_anymore_at_the/" },
    ["methodraidtools"] = { severity = "medium", note = "Icy-veins interview with Ion", link = "https://www.icy-veins.com/wow/news/blizzard-confirms-major-midnight-changes-in-exclusive-icy-veins-interview/" },
    ["mythicdungeontools"] = { severity = "low", note = "Day 1 Addons Update", link = "https://us.forums.blizzard.com/en/wow/t/day-1-alpha-ui-and-addons-update/2177122" },
    ["omnicd"] = { severity = "critical", note = "Icy-veins interview with Ion", link = "https://www.icy-veins.com/wow/news/blizzard-confirms-major-midnight-changes-in-exclusive-icy-veins-interview/" },
    ["rclootcouncil"] = { severity = "low", note = "Day 1 Addons Update", link = "https://us.forums.blizzard.com/en/wow/t/day-1-alpha-ui-and-addons-update/2177122" },
    ["weakauras"] = { severity = "critical", note = "No WeakAuras Addon for Midnight", link = "https://www.wowhead.com/news/no-weakauras-addon-for-midnight-378740" },
  }
}
